const skills = [
  "react.svg",
  "nextjs.svg",
  "vue.svg",
  "js.svg",
  "html.svg",
  "css.svg",
  "php.svg", 
  "framer-motion.svg",
  "nodejs.svg",
  "ex.svg",  
  "express.svg",
  "python.svg",
  "bootstrap.svg",
  "git.svg",
  "github.svg",
  "sql.svg",
  "mysql.svg", 
  "mongodb.svg",
  "tailwind.svg",
  "vscode.svg",
  "neovim.svg",
  "intellij.svg",
  "pycharm.svg",
  "aws.svg",
  "heroku.svg",
  "windows.svg",
  "apple.svg",
  "linux.svg",
]; // Add or remove skills here, make sure to include the image respective to the skill inside the public/skills folder and use the correct file extension

export default skills;
